### ISSUE TITLE
`Uncaught Error: Map container is being reused by another instance` from second manual search

### ISSUE THREAD

**Issue by MustakAbsarKhan** [MustakAbsarKhan/ip-address-tracker#1]
This error appears at the second search -
`Map.js:745 Uncaught Error: Map container is being reused by another instance
- at i.remove (Map.js:745:10)
- at HTMLButtonElement.mapOff (index.js:136:25)`

**Comment by MustakAbsarKhan** [comment]
Problem Resolved By Separetely Calling Marker in this commit - `7ba04d7b74a30ead55c0ddaae34a7df3a924a2b5`
